### ISSUE TITLE
Service Worker register failed because website uses old protocol

### ISSUE THREAD

**Issue by diverent2** [lkozyr/weatherium-app#1]
The website http://weather-app-20180703.epizy.com/ is still on the old http web protocol http which does not support service workers.

If possible, make sure your server runs "https" :)

![ice_screenshot_20180715-202612](https://user-images.githubusercontent.com/24892204/42736898-15f062b6-886e-11e8-8d6a-863d0051804f.png)

**Comment by lkozyr** [comment]
@MaximilianUE, I have deployed this project to a free hosting, and they do not provide https in their free plans. Also I am using third-party data providers (free plans as well), and some of them provide http API URL only for the free subscriptions.   
Thus even if I use https on my hosting, I will get CORS when connecting to third party data provider from https to http. 
This is just a learning project for me,  also project does not gather any login credentials or other sensitive data so I consider http only solution as 'acceptable' so far.

Anyways, thank you for the report, I will take a look at the service worker exception and try to at least get rid of console error message.

**Comment by lkozyr** [comment]
Service worker has been removed as https is not available anyways: https://github.com/lkozyr/weatherium-app/commit/475174e9cd44c3b6470a1e082121e892dbf5bb35
Closing the issue.

**Comment by DanielRuf** [comment]
In the future we could try GitHub pages with https if this is an option.

Let us know if you need some assistance.

Cool project 👍

**Comment by lkozyr** [comment]
Thank you @DanielRuf  ;-)
HTTPS will not work for this project anyways as I do not plan to buy a paid subscription to one of the data providers services, and in free plan they allow only http access. But you are right, GitHub pages is a great option if https is required, so I think I will try it with some of my next projects  😉

**Comment by DanielRuf** [comment]
You can then try the npm package `gh-pages`, oten this is already part of `npm run deploy`.
